// actionTypes.js

// Fetch affirmations
export const FETCH_AFFIRMATIONS_REQUEST = "FETCH_AFFIRMATIONS_REQUEST";
export const FETCH_AFFIRMATIONS_SUCCESS = "FETCH_AFFIRMATIONS_SUCCESS";
export const FETCH_AFFIRMATIONS_FAILURE = "FETCH_AFFIRMATIONS_FAILURE";

// Add affirmation
export const ADD_AFFIRMATION_REQUEST = "ADD_AFFIRMATION_REQUEST";
export const ADD_AFFIRMATION_SUCCESS = "ADD_AFFIRMATION_SUCCESS";
export const ADD_AFFIRMATION_FAILURE = "ADD_AFFIRMATION_FAILURE";

// Update affirmation
export const UPDATE_AFFIRMATION_REQUEST = "UPDATE_AFFIRMATION_REQUEST";
export const UPDATE_AFFIRMATION_SUCCESS = "UPDATE_AFFIRMATION_SUCCESS";
export const UPDATE_AFFIRMATION_FAILURE = "UPDATE_AFFIRMATION_FAILURE";

// Delete affirmation
export const DELETE_AFFIRMATION_REQUEST = "DELETE_AFFIRMATION_REQUEST";
export const DELETE_AFFIRMATION_SUCCESS = "DELETE_AFFIRMATION_SUCCESS";
export const DELETE_AFFIRMATION_FAILURE = "DELETE_AFFIRMATION_FAILURE";
