// ==================== TOKEN LIST ====================
export const FETCH_USER_TOKENS_REQUEST = "FETCH_USER_TOKENS_REQUEST";
export const FETCH_USER_TOKENS_SUCCESS = "FETCH_USER_TOKENS_SUCCESS";
export const FETCH_USER_TOKENS_FAILURE = "FETCH_USER_TOKENS_FAILURE";
