// redeemSubscriptionActionTypes.js

// ================= Fetch redeem subscriptions =================
export const FETCH_REDEEM_SUBSCRIPTIONS_REQUEST = "FETCH_REDEEM_SUBSCRIPTIONS_REQUEST";
export const FETCH_REDEEM_SUBSCRIPTIONS_SUCCESS = "FETCH_REDEEM_SUBSCRIPTIONS_SUCCESS";
export const FETCH_REDEEM_SUBSCRIPTIONS_FAILURE = "FETCH_REDEEM_SUBSCRIPTIONS_FAILURE";

// ================= Add redeem subscription =================
export const ADD_REDEEM_SUBSCRIPTION_REQUEST = "ADD_REDEEM_SUBSCRIPTION_REQUEST";
export const ADD_REDEEM_SUBSCRIPTION_SUCCESS = "ADD_REDEEM_SUBSCRIPTION_SUCCESS";
export const ADD_REDEEM_SUBSCRIPTION_FAILURE = "ADD_REDEEM_SUBSCRIPTION_FAILURE";

// ================= Update redeem subscription =================
export const UPDATE_REDEEM_SUBSCRIPTION_REQUEST = "UPDATE_REDEEM_SUBSCRIPTION_REQUEST";
export const UPDATE_REDEEM_SUBSCRIPTION_SUCCESS = "UPDATE_REDEEM_SUBSCRIPTION_SUCCESS";
export const UPDATE_REDEEM_SUBSCRIPTION_FAILURE = "UPDATE_REDEEM_SUBSCRIPTION_FAILURE";

// ================= Delete redeem subscription =================
export const DELETE_REDEEM_SUBSCRIPTION_REQUEST = "DELETE_REDEEM_SUBSCRIPTION_REQUEST";
export const DELETE_REDEEM_SUBSCRIPTION_SUCCESS = "DELETE_REDEEM_SUBSCRIPTION_SUCCESS";
export const DELETE_REDEEM_SUBSCRIPTION_FAILURE = "DELETE_REDEEM_SUBSCRIPTION_FAILURE";
