export const FETCH_USER_XP_POINTS_REQUEST = "FETCH_USER_XP_POINTS_REQUEST";
export const FETCH_USER_XP_POINTS_SUCCESS = "FETCH_USER_XP_POINTS_SUCCESS";
export const FETCH_USER_XP_POINTS_FAILURE = "FETCH_USER_XP_POINTS_FAILURE";
