// Fetch rituals
export const FETCH_RITUALS_REQUEST = "FETCH_RITUALS_REQUEST";
export const FETCH_RITUALS_SUCCESS = "FETCH_RITUALS_SUCCESS";
export const FETCH_RITUALS_FAILURE = "FETCH_RITUALS_FAILURE";

// Add ritual
export const ADD_RITUAL_REQUEST = "ADD_RITUAL_REQUEST";
export const ADD_RITUAL_SUCCESS = "ADD_RITUAL_SUCCESS";
export const ADD_RITUAL_FAILURE = "ADD_RITUAL_FAILURE";

// Update ritual
export const UPDATE_RITUAL_REQUEST = "UPDATE_RITUAL_REQUEST";
export const UPDATE_RITUAL_SUCCESS = "UPDATE_RITUAL_SUCCESS";
export const UPDATE_RITUAL_FAILURE = "UPDATE_RITUAL_FAILURE";

// Delete ritual
export const DELETE_RITUAL_REQUEST = "DELETE_RITUAL_REQUEST";
export const DELETE_RITUAL_SUCCESS = "DELETE_RITUAL_SUCCESS";
export const DELETE_RITUAL_FAILURE = "DELETE_RITUAL_FAILURE";
