// Fetch moods
export const FETCH_MOODS_REQUEST = "FETCH_MOODS_REQUEST";
export const FETCH_MOODS_SUCCESS = "FETCH_MOODS_SUCCESS";
export const FETCH_MOODS_FAILURE = "FETCH_MOODS_FAILURE";

// Add mood
export const ADD_MOOD_REQUEST = "ADD_MOOD_REQUEST";
export const ADD_MOOD_SUCCESS = "ADD_MOOD_SUCCESS";
export const ADD_MOOD_FAILURE = "ADD_MOOD_FAILURE";

// Update mood
export const UPDATE_MOOD_REQUEST = "UPDATE_MOOD_REQUEST";
export const UPDATE_MOOD_SUCCESS = "UPDATE_MOOD_SUCCESS";
export const UPDATE_MOOD_FAILURE = "UPDATE_MOOD_FAILURE";

// Delete mood
export const DELETE_MOOD_REQUEST = "DELETE_MOOD_REQUEST";
export const DELETE_MOOD_SUCCESS = "DELETE_MOOD_SUCCESS";
export const DELETE_MOOD_FAILURE = "DELETE_MOOD_FAILURE";
