// Fetch CMS pages
export const FETCH_CMS_REQUEST = "FETCH_CMS_REQUEST";
export const FETCH_CMS_SUCCESS = "FETCH_CMS_SUCCESS";
export const FETCH_CMS_FAILURE = "FETCH_CMS_FAILURE";

// Add CMS
export const ADD_CMS_REQUEST = "ADD_CMS_REQUEST";
export const ADD_CMS_SUCCESS = "ADD_CMS_SUCCESS";
export const ADD_CMS_FAILURE = "ADD_CMS_FAILURE";

// Update CMS
export const UPDATE_CMS_REQUEST = "UPDATE_CMS_REQUEST";
export const UPDATE_CMS_SUCCESS = "UPDATE_CMS_SUCCESS";
export const UPDATE_CMS_FAILURE = "UPDATE_CMS_FAILURE";
