// actionTypes.js

// Fetch category plans
export const FETCH_CATEGORY_PLANS_REQUEST = "FETCH_CATEGORY_PLANS_REQUEST";
export const FETCH_CATEGORY_PLANS_SUCCESS = "FETCH_CATEGORY_PLANS_SUCCESS";
export const FETCH_CATEGORY_PLANS_FAILURE = "FETCH_CATEGORY_PLANS_FAILURE";

// Add category plan
export const ADD_CATEGORY_PLAN_REQUEST = "ADD_CATEGORY_PLAN_REQUEST";
export const ADD_CATEGORY_PLAN_SUCCESS = "ADD_CATEGORY_PLAN_SUCCESS";
export const ADD_CATEGORY_PLAN_FAILURE = "ADD_CATEGORY_PLAN_FAILURE";

// Update category plan
export const UPDATE_CATEGORY_PLAN_REQUEST = "UPDATE_CATEGORY_PLAN_REQUEST";
export const UPDATE_CATEGORY_PLAN_SUCCESS = "UPDATE_CATEGORY_PLAN_SUCCESS";
export const UPDATE_CATEGORY_PLAN_FAILURE = "UPDATE_CATEGORY_PLAN_FAILURE";

// Delete category plan
export const DELETE_CATEGORY_PLAN_REQUEST = "DELETE_CATEGORY_PLAN_REQUEST";
export const DELETE_CATEGORY_PLAN_SUCCESS = "DELETE_CATEGORY_PLAN_SUCCESS";
export const DELETE_CATEGORY_PLAN_FAILURE = "DELETE_CATEGORY_PLAN_FAILURE";
