// actionTypes.js

// Fetch redeem plans
export const FETCH_REDEEM_PLANS_REQUEST = "FETCH_REDEEM_PLANS_REQUEST";
export const FETCH_REDEEM_PLANS_SUCCESS = "FETCH_REDEEM_PLANS_SUCCESS";
export const FETCH_REDEEM_PLANS_FAILURE = "FETCH_REDEEM_PLANS_FAILURE";

// Add redeem plan
export const ADD_REDEEM_PLAN_REQUEST = "ADD_REDEEM_PLAN_REQUEST";
export const ADD_REDEEM_PLAN_SUCCESS = "ADD_REDEEM_PLAN_SUCCESS";
export const ADD_REDEEM_PLAN_FAILURE = "ADD_REDEEM_PLAN_FAILURE";

// Update redeem plan
export const UPDATE_REDEEM_PLAN_REQUEST = "UPDATE_REDEEM_PLAN_REQUEST";
export const UPDATE_REDEEM_PLAN_SUCCESS = "UPDATE_REDEEM_PLAN_SUCCESS";
export const UPDATE_REDEEM_PLAN_FAILURE = "UPDATE_REDEEM_PLAN_FAILURE";

// Delete redeem plan
export const DELETE_REDEEM_PLAN_REQUEST = "DELETE_REDEEM_PLAN_REQUEST";
export const DELETE_REDEEM_PLAN_SUCCESS = "DELETE_REDEEM_PLAN_SUCCESS";
export const DELETE_REDEEM_PLAN_FAILURE = "DELETE_REDEEM_PLAN_FAILURE";
