export const FETCH_PAYMENTLOGS_REQUEST = "FETCH_PAYMENTLOGS_REQUEST";
export const FETCH_PAYMENTLOGS_SUCCESS = "FETCH_PAYMENTLOGS_SUCCESS";
export const FETCH_PAYMENTLOGS_FAILURE = "FETCH_PAYMENTLOGS_FAILURE";
